/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2016-04-30 17:20:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import br.feevale.controle.ControleLogin;

public final class Pagina_005fInicial_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("br.feevale.controle.ControleLogin");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

//Comentado por Antonio

String nome = request.getParameter( "nome" );
    String senha = request.getParameter( "senha" );
    String msg = null;
    
    if( nome != null && senha != null ) {
    	ControleLogin cl = new ControleLogin( nome, senha );
    	
    	if( cl.isUsuarioOk() ) {
    		session.setAttribute( "UsuarioLogado", cl );
    		response.sendRedirect( "./Pagina_usuário.jsp" );
    		return;
    	} else {
    		msg = "Nome ou senha inválidos";
    		session.removeAttribute( "UsuarioLogado" );
    	}
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("   <head>\r\n");
      out.write("      <meta charset=\"utf-8\">\r\n");
      out.write("      <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("      <meta name=\"description\" content=\"\">\r\n");
      out.write("      <meta name=\"author\" content=\"\">\r\n");
      out.write("      <title>Pagina Inicial</title>\r\n");
      out.write("      <!-- Bootstrap Core CSS -->\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("      <!-- Custom Fonts -->\r\n");
      out.write("      <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>\r\n");
      out.write("      <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"font-awesome/css/font-awesome.min.css\" type=\"text/css\">\r\n");
      out.write("      <!-- Plugin CSS -->\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"css/animate.min.css\" type=\"text/css\">\r\n");
      out.write("      <!-- Custom CSS -->\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"css/creative.css\" type=\"text/css\">\r\n");
      out.write("      <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("      <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("      <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("      <![endif]-->\r\n");
      out.write("      <link href= \"meus_efeitos/css/Meucss.css\" rel=\"stylesheet\">\r\n");
      out.write("      <script type=\"meus_efeitos/js/meus_efeitos.js\" charset=\"UTF-8\"></script>\r\n");
      out.write("      <script src=\"http://code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("      <script src=\"http://netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("   </head>\r\n");
      out.write("   <body id=\"page-top\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("         <nav id=\"mainNav\" class=\"navbar navbar-default navbar-fixed-top\">\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("               <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("               <div class=\"navbar-header\">\r\n");
      out.write("                  <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("                  <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                  <span class=\"icon-bar\"></span>\r\n");
      out.write("                  <span class=\"icon-bar\"></span>\r\n");
      out.write("                  <span class=\"icon-bar\"></span>\r\n");
      out.write("                  </button>\r\n");
      out.write("                  <a class=\"navbar-brand page-scroll\" href=\"#page-top\">ChegoLá </a>\r\n");
      out.write("               </div>\r\n");
      out.write("               <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("               <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("                  <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <a class=\"page-scroll\" href=\"#about\">Cadastre-se</a>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <a class=\"page-scroll\" href=\"#services\">Serviços</a>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <a class=\"page-scroll\" href=\"#\" data-toggle=\"modal\" data-target=\"#exampleModal\" >Entrar</a>\r\n");
      out.write("                     </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.navbar-collapse -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- /.container-fluid -->\r\n");
      out.write("      <!-- AQUI COMEÃA A PÃGINA DE LOGIN -->\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("      <div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\">\r\n");
      out.write("      <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("      <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("      <h4>Realizar Login</h4>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("           <form class=\"form-signin\" method=\"post\">\r\n");
      out.write("\t      <div class=\"form-group\">\r\n");
      out.write("\t\t      <label for=\"recipient-name\" name=\"nome\" class=\"control-label\">E-mail:</label>\r\n");
      out.write("\t\t      <input type=\"text\" name=\"nome\" class=\"form-control\" placeholder=\"login\"id=\"recipient-name\">  \r\n");
      out.write("\t      </div>\r\n");
      out.write("\t         \r\n");
      out.write("\t      <div class=\"form-group\">\r\n");
      out.write("\t\t      <label for=\"recipient-name\" class=\"control-label\">Senha:</label>\r\n");
      out.write("\t\t      <input type=\"password\" name=\"senha\" class=\"form-control\" placeholder=\"senha\">  \r\n");
      out.write("\t      </div>\r\n");
      out.write("\t      \r\n");
      out.write("\t             ");
	if( msg != null ) { 
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"alert alert-danger\" role=\"alert\">\r\n");
      out.write("\t\t\t\t  <span class=\"glyphicon glyphicon-exclamation-sign\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t  <span class=\"sr-only\">Error:</span>\r\n");
      out.write("\t\t\t\t  Login ou senha inválido\r\n");
      out.write("\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t  ");
  } 
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("      <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Cancelar</button>\r\n");
      out.write("      <button type=\"submit\" class=\"btn btn-primary\" value=\"Login\">Entrar</button>\r\n");
      out.write("  \r\n");
      out.write("     \r\n");
      out.write("       </form>\r\n");
      out.write("             </div>\r\n");
      out.write("       \r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- AQUI TERMINA A PÃGINA DE LOGIN -->\r\n");
      out.write("      </nav>\r\n");
      out.write("      <header>\r\n");
      out.write("         <div class=\"header-content\">\r\n");
      out.write("            <div class=\"header-content-inner\">\r\n");
      out.write("               <video id=\"video\" class=\"video\" muted loop>\r\n");
      out.write("                  <source src=\"https://www.html5dev.com.br/blog/wp-content/uploads/2015/05/bridge_timelapse_271.webm\" type=\"video/webm\"/>\r\n");
      out.write("                  <!-- <source src=\"https://www.html5dev.com.br/blog/wp-content/uploads/2015/05/bridge_timelapse_271.mp4\" type=\"video/mp4\"/>\r\n");
      out.write("                     <source src=\"https://www.html5dev.com.br/blog/wp-content/uploads/2015/05/bridge_timelapse_271.ogv\" type=\"video/ogg\"/>\r\n");
      out.write("                     -->\r\n");
      out.write("               </video>\r\n");
      out.write("               <h2 style=\"font-size: 50px; font-family:Helvetica\">\r\n");
      out.write("               A Melhor empresa em viagens Aéreas e Translados</h>\r\n");
      out.write("               <hr>\r\n");
      out.write("               <div class=\"container\">\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                     <div class=\"col-xs-9\">\r\n");
      out.write("                        <form class=\"form-horizontal\">\r\n");
      out.write("                           <div class=\"form-group form-group-lg\">\r\n");
      out.write("                              <div class=\"col-sm-10\" >\r\n");
      out.write("                                 <input  style=\"margin-left: 130px\"; class=\"form-control\" type=\"text\" id=\"formGroupInputLarge\" placeholder=\"Pesquisar um local \">\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </header>\r\n");
      out.write("      <section class=\"bg-primary\" id=\"about\">\r\n");
      out.write("         <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <div class=\"col-lg-8 col-lg-offset-2 text-center\">\r\n");
      out.write("                  <h2 class=\"section-heading\">Nós temos o que você precisa!</h2>\r\n");
      out.write("                  <hr class=\"light\">\r\n");
      out.write("                  <p class=\"text-faded\">OS melhores serviços de translado e passagens aéreas!</p>\r\n");
      out.write("                  <a href=\"#\" class=\"btn btn-default btn-xl\">Conhecer!</a>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </section>\r\n");
      out.write("      <section id=\"services\">\r\n");
      out.write("         <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <div class=\"col-lg-12 text-center\">\r\n");
      out.write("                  <h2 class=\"section-heading\">Conheça os serviços</h2>\r\n");
      out.write("                  <hr class=\"primary\">\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <div class=\"col-lg-3 col-md-6 text-center\">\r\n");
      out.write("                  <div class=\"service-box\">\r\n");
      out.write("                     <i class=\"fa fa-4x fa-diamond wow bounceIn text-primary\"></i>\r\n");
      out.write("                     <h3>Empresas Gold</h3>\r\n");
      out.write("                     <p class=\"text-muted\">Empresa conceituada no mercado.</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-lg-3 col-md-6 text-center\">\r\n");
      out.write("                  <div class=\"service-box\">\r\n");
      out.write("                     <i class=\"fa fa-4x fa-paper-plane wow bounceIn text-primary\" data-wow-delay=\".1s\"></i>\r\n");
      out.write("                     <h3>Pronto para Voar</h3>\r\n");
      out.write("                     <p class=\"text-muted\">PAssagens aéreas com melhor preço!</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-lg-3 col-md-6 text-center\">\r\n");
      out.write("                  <div class=\"service-box\">\r\n");
      out.write("                     <i class=\"fa fa-4x fa-newspaper-o wow bounceIn text-primary\" data-wow-delay=\".2s\"></i>\r\n");
      out.write("                     <h3>Cadastro</h3>\r\n");
      out.write("                     <p class=\"text-muted\">Cadastro rápido e sem burocracia</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-lg-3 col-md-6 text-center\">\r\n");
      out.write("                  <div class=\"service-box\">\r\n");
      out.write("                     <i class=\" fa fa-4x fa-heart wow bounceIn text-primary\" data-wow-delay=\".3s\"></i>\r\n");
      out.write("                     <h3>Viagem com a Familia</h3>\r\n");
      out.write("                     <p class=\"text-muted\"></p>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </section>\r\n");
      out.write("      <section class=\"no-padding\" id=\"portfolio\">\r\n");
      out.write("         <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"row no-gutter\">\r\n");
      out.write("               <div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("                  <a href=\"#\" class=\"portfolio-box\">\r\n");
      out.write("                     <img src=\"img/portfolio/1.1.jpg\" class=\"img-responsive\" alt=\"\">\r\n");
      out.write("                     <div class=\"portfolio-box-caption\">\r\n");
      out.write("                        <div class=\"portfolio-box-caption-content\">\r\n");
      out.write("                           <div class=\"project-category text-faded\">\r\n");
      out.write("                              Turismo\t\r\n");
      out.write("                           </div>\r\n");
      out.write("                           <div class=\"project-name\">\r\n");
      out.write("                              Cachoeiras\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("                  <a href=\"#\" class=\"portfolio-box\">\r\n");
      out.write("                     <img src=\"img/portfolio/2.2.jpg\" class=\"img-responsive\" alt=\"\">\r\n");
      out.write("                     <div class=\"portfolio-box-caption\">\r\n");
      out.write("                        <div class=\"portfolio-box-caption-content\">\r\n");
      out.write("                           <div class=\"project-category text-faded\">\r\n");
      out.write("                              Turismo\r\n");
      out.write("                           </div>\r\n");
      out.write("                           <div class=\"project-name\">\r\n");
      out.write("                             Praias\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("                  <a href=\"#\" class=\"portfolio-box\">\r\n");
      out.write("                     <img src=\"img/portfolio/3.3.jpg\" class=\"img-responsive\" alt=\"\">\r\n");
      out.write("                     <div class=\"portfolio-box-caption\">\r\n");
      out.write("                        <div class=\"portfolio-box-caption-content\">\r\n");
      out.write("                           <div class=\"project-category text-faded\">\r\n");
      out.write("                              Internacional\r\n");
      out.write("                           </div>\r\n");
      out.write("                           <div class=\"project-name\">\r\n");
      out.write("\t                         Paris\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("                  <a href=\"#\" class=\"portfolio-box\">\r\n");
      out.write("                     <img src=\"img/portfolio/4.4.jpg\" class=\"img-responsive\" alt=\"\">\r\n");
      out.write("                     <div class=\"portfolio-box-caption\">\r\n");
      out.write("                        <div class=\"portfolio-box-caption-content\">\r\n");
      out.write("                           <div class=\"project-category text-faded\">\r\n");
      out.write("                              Turismo\r\n");
      out.write("                           </div>\r\n");
      out.write("                           <div class=\"project-name\">\r\n");
      out.write("                              Rio de Janeiro\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("                  <a href=\"#\" class=\"portfolio-box\">\r\n");
      out.write("                     <img src=\"img/portfolio/5.5.jpg\" class=\"img-responsive\" alt=\"\">\r\n");
      out.write("                     <div class=\"portfolio-box-caption\">\r\n");
      out.write("                        <div class=\"portfolio-box-caption-content\">\r\n");
      out.write("                           <div class=\"project-category text-faded\">\r\n");
      out.write("                              Trabalho\r\n");
      out.write("                           </div>\r\n");
      out.write("                           <div class=\"project-name\">\r\n");
      out.write("                             São Paulo\t\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("                  <a href=\"#\" class=\"portfolio-box\">\r\n");
      out.write("                     <img src=\"img/portfolio/6.6.png\" class=\"img-responsive\" alt=\"\">\r\n");
      out.write("                     <div class=\"portfolio-box-caption\">\r\n");
      out.write("                        <div class=\"portfolio-box-caption-content\">\r\n");
      out.write("                           <div class=\"project-category text-faded\">\r\n");
      out.write("                              Turismo\r\n");
      out.write("                           </div>\r\n");
      out.write("                           <div class=\"project-name\">\r\n");
      out.write("                             Curitiba\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </a>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </section>\r\n");
      out.write("      <section id=\"contact\">\r\n");
      out.write("         <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <div class=\"col-lg-8 col-lg-offset-2 text-center\">\r\n");
      out.write("                  <h2 class=\"section-heading\">Partiu Viagem ;)</h2>\r\n");
      out.write("                  <hr class=\"primary\">\r\n");
      out.write("                  <p>Entre em contato com nossos canais de comunicação!</p>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-lg-4 col-lg-offset-2 text-center\">\r\n");
      out.write("                  <i class=\"fa fa-phone fa-3x wow bounceIn\"></i>\r\n");
      out.write("                  <p>(51) 3577-4871</p>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-lg-4 text-center\">\r\n");
      out.write("                  <i class=\"fa fa-envelope-o fa-3x wow bounceIn\" data-wow-delay=\".1s\"></i>\r\n");
      out.write("                  <p><a href=\"mailto:your-email@your-domain.com\">chegola@gmail.com</a></p>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </section>\r\n");
      out.write("      <!-- jQuery -->\r\n");
      out.write("      <script src=\"js/jquery.js\"></script>\r\n");
      out.write("      <!-- Bootstrap Core JavaScript -->\r\n");
      out.write("      <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("      <!-- Plugin JavaScript -->\r\n");
      out.write("      <script src=\"js/jquery.easing.min.js\"></script>\r\n");
      out.write("      <script src=\"js/jquery.fittext.js\"></script>\r\n");
      out.write("      <script src=\"js/wow.min.js\"></script>\r\n");
      out.write("      <!-- Custom Theme JavaScript -->\r\n");
      out.write("      <script type=\"text/javascript\">\r\n");
      out.write("         $('#exampleModal').on('show.bs.modal', function (event) {\r\n");
      out.write("           var button = $(event.relatedTarget) // Button that triggered the modal\r\n");
      out.write("           var recipient = button.data('whatever') // Extract info from data-* attributes\r\n");
      out.write("           // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).\r\n");
      out.write("           // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.\r\n");
      out.write("           var modal = $(this)\r\n");
      out.write("           modal.find('.modal-title').text('New message to ' + recipient)\r\n");
      out.write("           modal.find('.modal-body input').val(recipient)\r\n");
      out.write("         })\r\n");
      out.write("         \r\n");
      out.write("      </script>\r\n");
      out.write("      <script src=\"js/creative.js\"></script>\r\n");
      out.write("      <script>\r\n");
      out.write("         (function () {\r\n");
      out.write("         var video = document.getElementById('video');\r\n");
      out.write("         video.addEventListener('canplay', function () {\r\n");
      out.write("           video.play();\r\n");
      out.write("         });\r\n");
      out.write("         }());\r\n");
      out.write("         //@ sourceURL=pen.js\r\n");
      out.write("      </script>\r\n");
      out.write("      <script>\r\n");
      out.write("         if (document.location.search.match(/type=embed/gi)) {\r\n");
      out.write("           window.parent.postMessage(\"resize\", \"*\");\r\n");
      out.write("         }\r\n");
      out.write("      </script>\r\n");
      out.write("   </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
